spring:
  data:
    mongodb:
      uri: mongodb://alibou:alibou@localhost:27017/notification?authSource=admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  mail:
    host: localhost
    port: 1025
    username: alibou
    password: alibou
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8040
