spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/order?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application: 
  config:
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payment
    product-url: http://localhost:8222/api/v1/products
server:
  port: 8070
