spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/payment?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.example.ecommerce.notification.PaymentNotificationRequest
    # consumer:
    #   bootstrap-servers: localhost:9092
    #   group-id: payment-group
    #   auto-offset-reset: earliest
    #   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #   properties:
    #     spring.json.trusted.packages: '*'

server:
  port: 8060
