spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/product
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

server:
  port: 8050
